const fs=require('fs'), vm=require('vm');
function el(text=''){return {textContent:text,value:text,style:{},classList:{contains:()=>false},getBoundingClientRect:()=>({width:10,height:10}),dispatchEvent(){},scrollIntoView(){},click(){this.clicked=true},closest(){return null}}}
const fakeDoc={body:{textContent:'Node ID: 123',innerText:'Contexte Drupal simulé'},title:'Page test',querySelector(sel){if(sel.includes('title'))return el('Titre'); if(sel.includes('ck-editor')||sel==='textarea')return el('<p>Avant</p>'); return null;},querySelectorAll(sel){if(sel.includes('ui-autocomplete')||sel.includes('[role="option"]'))return [el('Formateurs (6625)')]; return [];},createElement(){return el('')},addEventListener(){},head:{appendChild(){}}};
const ctx={window:{EAFCAgent:{},confirm:()=>true,location:{href:'https://intranet.ac-poitiers.fr/node/123/edit',pathname:'/node/123/edit'},URL:{createObjectURL:()=>'',revokeObjectURL(){}}},document:fakeDoc,localStorage:{s:{},getItem(k){return this.s[k]||null},setItem(k,v){this.s[k]=v}},location:{href:'https://intranet.ac-poitiers.fr/node/123/edit',pathname:'/node/123/edit'},performance:{now:()=>Date.now()},Event:class{constructor(t,o){this.type=t}},MouseEvent:class{constructor(t,o){this.type=t}},getComputedStyle:()=>({visibility:'visible',display:'block'}),Blob:class{},alert(){},console,setTimeout};
ctx.window.document=fakeDoc; ctx.window.localStorage=ctx.localStorage; ctx.window.Event=ctx.Event; ctx.window.MouseEvent=ctx.MouseEvent; ctx.window.getComputedStyle=ctx.getComputedStyle; ctx.window.performance=ctx.performance; ctx.window.Blob=ctx.Blob; ctx.window.setTimeout=setTimeout; vm.createContext(ctx);
['src/agent/core/model.js','src/agent/core/state.js','src/agent/core/report.js','src/agent/services/click.js','src/agent/services/dom.js','src/agent/services/autocomplete.js','src/agent/services/taxonomy.js','src/agent/services/fancytree.js','src/agent/services/sofia.js','src/agent/core/executor.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f}));
const A=ctx.window.EAFCAgent; function assert(c,m){if(!c)throw new Error(m)}
let v2=A.core.normalizeJob({schemaVersion:'2.0',jobId:'j1',workflow:'update_taxonomy',targets:[{canonicalId:'t1',nodeId:'123'}],operations:[{targetId:'t1',field:'thematics',op:'add',value:['6202']}],safety:{simulation:true}}); assert(v2.targets[0].operations.length===1,'job v2 lié aux cibles');
let legacy=A.core.normalizeJob({type:'update_drupal_pages',version:'3.0',items:[{targets:[{nodeId:'123',pageUrl:'/node/123/edit',changes:{title:{operation:'replace',value:'X'}},expectedBefore:{title:'Old'}}]}]}); assert(legacy.workflow==='update_content'&&legacy.operations[0].field==='title','legacy update converti');
let bulk=A.core.normalizeJob({type:'bulk_drupal_theme_public_update',targets:[{nodeId:'123',changes:{metiersPublics:{operation:'add',values:['A']}}}]}); assert(bulk.workflow==='update_taxonomy'&&bulk.operations[0].op==='add','legacy taxonomy converti');
assert(A.autocomplete.matchesSuggestion('Formateurs (6625)','6625')&&A.autocomplete.matchesSuggestion('Formateurs (6625)','Formateurs'),'autocomplete id/libellé');
A.taxonomy.applyTheme({field:'thematics',op:'add',value:['6202']},'create',true).then(r=>{assert(r.finalAdded.includes('EAFC poitiers')&&r.finalAdded.includes('6331'),'thématiques obligatoires création'); return A.taxonomy.applyTheme({field:'thematics',op:'add',value:['6202']},'update_taxonomy',true)}).then(r=>{assert(!r.finalAdded.includes('6331'),'pas ajout obligatoire en mise à jour'); let target=v2.targets[0]; A.executor.validateTarget(target,v2); assert(A.executor.workflowOf(target,v2)==='update_taxonomy','workflow opérationnel'); console.log('agent-core tests ok');}).catch(e=>{throw e});
