const fs=require('fs'), vm=require('vm');
const ctx={window:{EAFC:{}}, console, crypto:{subtle:{}}, document:{}, Blob:class{}}; ctx.EAFC=ctx.window.EAFC; vm.createContext(ctx);
['src/studio/core/model.js','src/studio/core/normalize.js','src/studio/core/diff.js','src/studio/adapters/importers.js','src/studio/core/matching.js','src/studio/core/job.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f}));
const A=ctx.window.EAFC; A.excel={isInventorySheet:s=>s.headers.includes('Node ID Drupal'), isSofiaSheet:s=>s.headers.includes('Dispositif : code')};
function assert(c,m){if(!c)throw new Error(m)}
function sheet(name,rows){const headers=Object.keys(rows[0]||{}); return {name,headers,objects:rows.map((r,i)=>Object.assign({_sheet:name,_row:i+2},r)),diagnostic:{aliases:headers.map(h=>({header:h,alias:({
 'Node ID Drupal':'nodeId','Lien de la page':'urlDrupal','Titre':'titleDrupal','Départements':'departments','Numéro de dispositif GAIA':'dispositifGaia','Numéro de module GAIA':'moduleGaia','Dispositif : code':'sofiaDispositif','Module : code':'sofiaModule','Groupe : identifiant':'sofiaGroup','Session':'session','Début':'start','Fin':'end','Modalité':'modality','UAI':'uai','Lieu':'location','Maximum':'capacity','Total inscrit':'registered','Préinscriptions : Publication : lien préinscription':'preRegistrationLink'}[h])})),unknown:[]}}}
const ovp=JSON.parse(fs.readFileSync('tests/fixtures/ovp-plan-emi.sample.json','utf8')); const ovpModels=A.importers.ovpToCanonical(ovp,'fixture'); assert(ovpModels.length===10,'OVP produit 10 parcours'); assert(ovpModels[0].objective==='Objectif 1'&&ovpModels[0].content==='Contenu 1','course.meta lu'); assert(ovpModels[0].dates.sessionsPresentiel.length===2&&ovpModels[0].dates.sessionsDistanciel.length===1,'sessions numériques acceptées');
const rec=JSON.parse(fs.readFileSync('tests/fixtures/recensement-drupal.sample.json','utf8')); const wb={sheets:rec.sheets.map(s=>sheet(s.name,s.rows))}; const pages=A.importers.inventoryRowsToCanonical(wb,'rec'); assert(pages.length===3,'feuilles T importées sans synthèse'); assert(pages[0].nodeId==='1001','Node ID conservé'); assert(pages[0].trainingCodes.dispositifCode==='26A0130001','dispositif GAIA conservé'); assert(JSON.stringify(pages[0].trainingCodes.moduleCodes)===JSON.stringify(['75001','75002']),'modules GAIA découpés exactement'); assert(pages[0].excelOrigin.sheetName==='T1_Test'&&pages[0].excelOrigin.rowNumber===2,'origine Excel conservée'); assert(new Set(pages.map(p=>p.nodeId)).size===3,'pages départementales non fusionnées');
const sof=JSON.parse(fs.readFileSync('tests/fixtures/sofia-plan-sessions.sample.json','utf8')); const swb={sheets:[sheet('Sofia',sof.rows)]}; const rows=A.importers.sofiaRows(swb); assert(rows[0].remainingSeats===8,'places restantes calculées uniquement numériques'); const m=A.matching.resolveGaiaToDrupal(rows,pages); assert(m.find(x=>x.row.uai.startsWith('016')&&x.row.moduleCode==='75001').best.nodeId==='1001','UAI 016 vers Node 1001'); assert(m.find(x=>x.row.uai.startsWith('017')&&x.row.moduleCode==='75001').best.nodeId==='1002','UAI 017 vers Node 1002'); const b=A.matching.resolveGaiaToDrupal([rows.find(r=>r.moduleCode==='75003')],pages)[0]; assert(b.candidates.some(c=>c.nodeId==='1003'&&!c.blocking),'page 16/17 accepte UAI 016');
const fallback=A.matching.fallbackSofiaMatches(A.model.createCanonical({canonicalId:'p',nodeId:'2000',titleDrupal:'Parcours EMI',departments:['16']}),rows,{'p|75001|G16':true}); assert(fallback[0].groups.length&&fallback[0].uai&&fallback[0].departments.length&&fallback[0].validated,'secours propose groupes UAI départements et validation manuelle'); const blocked=A.matching.getMappingExportBlockers([{row:rows[0],best:null,ambiguous:false}]); assert(blocked.some(b=>b.type==='node_id_missing'),'export bloqué sans Node ID'); const bad={workflow:'update_sofia',sources:[],pages:[A.model.createCanonical({canonicalId:'x',nodeId:'1',operations:[{field:'title',op:'replace',value:'X',selected:true}]})]}; assert(A.job.validateExport(bad).blocking,'workflow Sofia bloque champ interdit');
console.log('studio real sources tests ok');
