(function(EAFC){
  const A_NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
  async function unzipEntries(file){return await EAFC.zip.openZip(file);}
  function xml(txt){return new DOMParser().parseFromString(txt,'application/xml');}
  function text(el){return el?el.textContent:'';}
  function colName(ref){return String(ref||'').replace(/\d+/g,'');}
  function colIndex(col){let n=0; for(const ch of col)n=n*26+ch.charCodeAt(0)-64; return n-1;}
  async function parseWorkbook(file){const zip=await unzipEntries(file); const ss=[]; if(zip.file('xl/sharedStrings.xml')){const doc=xml(await zip.file('xl/sharedStrings.xml').async('text')); doc.querySelectorAll('si').forEach(si=>ss.push([...si.querySelectorAll('t')].map(t=>t.textContent).join('')));}
    const wb=xml(await zip.file('xl/workbook.xml').async('text')); const relDoc=xml(await zip.file('xl/_rels/workbook.xml.rels').async('text')); const rels={}; relDoc.querySelectorAll('Relationship').forEach(r=>rels[r.getAttribute('Id')]=r.getAttribute('Target'));
    const sheets=[]; for(const sh of wb.querySelectorAll('sheet')){const name=sh.getAttribute('name'); const rid=sh.getAttribute('r:id')||sh.getAttribute('id'); const path='xl/'+rels[rid].replace(/^\//,''); const doc=xml(await zip.file(path).async('text')); const merges=[...doc.querySelectorAll('mergeCell')].map(m=>m.getAttribute('ref')); const rows=[]; doc.querySelectorAll('sheetData row').forEach(row=>{const arr=[]; row.querySelectorAll('c').forEach(c=>{const idx=colIndex(colName(c.getAttribute('r'))); let v=text(c.querySelector('v')); if(c.getAttribute('t')==='s') v=ss[Number(v)]||''; const f=text(c.querySelector('f')); arr[idx]=f?`=${f}`:v;}); rows.push({number:Number(row.getAttribute('r')), values:arr.map(x=>x??'')});}); const sheet={name,order:sheets.length+1,dimension:doc.querySelector('dimension')?.getAttribute('ref')||'',merges,rows,headerRow:1,headers:[],objects:[],diagnostic:{recognized:[],unknown:[],mergedCells:merges,formulas:0,validations:doc.querySelectorAll('dataValidation').length}}; buildObjects(sheet); sheets.push(sheet);} return {name:file.name,sheets,originalFileName:file.name,parsedAt:new Date().toISOString()};}
  const ALIASES={'nodeId':['node id drupal','node id'],'urlDrupal':['lien de la page','url'],'titleDrupal':['titre'],'thematics':['thematiques saisies','thématiques saisies'],'publics':['metiers','métiers'],'status':['statut']};
  function recognizeHeader(h){const c=EAFC.normalize.canonicalHeader(h); return Object.entries(ALIASES).find(([k,vals])=>vals.includes(c))?.[0]||'';}
  function buildObjects(sheet){const first=sheet.rows.find(r=>r.values.some(Boolean)); if(!first)return; sheet.headerRow=first.number; sheet.headers=first.values.map(v=>String(v||'').trim()); sheet.objects=sheet.rows.filter(r=>r.number>first.number&&r.values.some(Boolean)).map(r=>{const o={_sheet:sheet.name,_row:r.number}; sheet.headers.forEach((h,i)=>{o[h||`Colonne ${i+1}`]=r.values[i]??'';}); return o;}); sheet.diagnostic.recognized=sheet.headers.filter(h=>recognizeHeader(h)); sheet.diagnostic.unknown=sheet.headers.filter(h=>h&&!recognizeHeader(h)); sheet.diagnostic.formulas=sheet.rows.reduce((n,r)=>n+r.values.filter(v=>String(v).startsWith('=')).length,0);}
  function isInventorySheet(sheet){const hs=sheet.headers.map(EAFC.normalize.canonicalHeader); return hs.includes('node id drupal')&&hs.includes('lien de la page')&&hs.includes('titre');}
  async function exportVersionedCopy(workbook, updates=[]){const content=JSON.stringify({type:'excel_inventory_update_plan',version:'2.0',source:workbook?.originalFileName||'',generatedAt:new Date().toISOString(),updates,historyAppendOnly:true},null,2); return new Blob([content],{type:'application/json'});}
  EAFC.excel={parseWorkbook,isInventorySheet,exportVersionedCopy,recognizeHeader};
})(window.EAFC=window.EAFC||{});
