(function(EAFC){
  async function unzipEntries(file){return await EAFC.zip.openZip(file);}
  function xml(txt){return new DOMParser().parseFromString(txt,'application/xml');}
  function text(el){return el?el.textContent:'';}
  function colName(ref){return String(ref||'').replace(/\d+/g,'');}
  function colIndex(col){let n=0; for(const ch of col)n=n*26+ch.charCodeAt(0)-64; return Math.max(0,n-1);}
  function excelDate(n){const v=Number(n); if(!Number.isFinite(v))return null; const d=new Date(Date.UTC(1899,11,30)+v*86400000); return d.toISOString().slice(0,10);}
  function readCell(c,shared){const f=text(c.querySelector('f')); if(f)return {value:'='+f,type:'formula',formula:f}; const type=c.getAttribute('t'); if(type==='s'){const idx=Number(text(c.querySelector('v'))); return {value:shared[idx]||'',type:'string'};} if(type==='inlineStr')return {value:[...c.querySelectorAll('t')].map(t=>t.textContent).join(''),type:'string'}; const raw=text(c.querySelector('v')); if(raw==='')return {value:'',type:'blank'}; if(type==='str')return {value:raw,type:'string'}; const num=Number(raw); return Number.isFinite(num)?{value:raw,type:'number',excelDate:excelDate(num)}:{value:raw,type:'string'};}
  function headerScore(values){const joined=values.map(EAFC.normalize.canonicalHeader).join('|'); return ['node id drupal','lien de la page','titre','id intention','titre du parcours','objectif general','contenu','dispositif code','module code','groupe identifiant','session','debut','fin','modalite','uai','lieu'].reduce((n,k)=>n+(joined.includes(k)?1:0),0);}
  function findHeaderRow(rows){let best=rows.find(r=>r.values.some(Boolean))||{number:1,values:[]}, score=-1; rows.slice(0,20).forEach(r=>{const s=headerScore(r.values); if(s>score){score=s; best=r;}}); return best;}
  const ALIASES={nodeId:['node id drupal','node id'],urlDrupal:['lien de la page','url','page url'],titleDrupal:['titre'],thematics:['thematiques saisies','thématiques saisies'],publics:['metiers','métiers'],status:['statut'],dispositifGaia:['numero de dispositif gaia','numéro de dispositif gaia','n dispositif gaia','code dispositif gaia','dispositif gaia'],moduleGaia:['numero de module gaia','numéro de module gaia','n module gaia','code module gaia','module gaia'],departments:['departements','départements'],intentionId:['id intention','identifiant intention'],requestTitle:['titre du parcours'],objective:['objectif general','objectif général','objectif general du parcours','objectif général du parcours'],content:['contenu','contenu de la formation'],sofiaDispositif:['dispositif code','dispositif : code'],sofiaModule:['module code','module : code'],sofiaGroup:['groupe identifiant','groupe : identifiant'],session:['session'],start:['debut','début'],end:['fin'],modality:['modalite','modalité'],uai:['uai'],rne:['rne'],location:['lieu'],territory:['territoire'],preRegistrationLink:['preinscriptions publication lien preinscription','préinscriptions publication lien préinscription','lien preinscription','lien préinscription'],capacity:['maximum','capacite','capacité','nombre maximal de places'],registered:['total inscrit','total preinscrit','total préinscrit']};
  function recognizeHeader(h){const c=EAFC.normalize.canonicalHeader(h); return Object.entries(ALIASES).find(([k,vals])=>vals.map(EAFC.normalize.canonicalHeader).includes(c))?.[0]||'';}
  function hasAliases(sheet,keys){const aliases=new Set(sheet.headers.map(recognizeHeader).filter(Boolean)); return keys.every(k=>aliases.has(k));}
  function classifyWorkbook(wb,name=''){const hasInv=wb.sheets.some(isInventorySheet), hasReq=wb.sheets.some(s=>hasAliases(s,['intentionId','requestTitle','objective','content'])), hasSofia=wb.sheets.some(s=>hasAliases(s,['sofiaDispositif','sofiaModule','sofiaGroup','session','start','end','modality','uai','location'])); if(hasInv)return 'recensement_excel'; if(hasReq)return 'demande_modification_excel'; if(hasSofia)return 'plan_sessions_sofia'; const n=name.toLowerCase(); if(n.includes('plan')&&n.includes('sessions'))return 'plan_sessions_sofia'; return 'excel_unknown';}
  function buildObjects(sheet){const header=findHeaderRow(sheet.rows); sheet.headerRow=header.number; sheet.headers=header.values.map(v=>String(v||'').trim()); sheet.objects=sheet.rows.filter(r=>r.number>header.number&&r.values.some(Boolean)).map(r=>{const o={_sheet:sheet.name,_row:r.number}; sheet.headers.forEach((h,i)=>{o[h||`Colonne ${i+1}`]=r.values[i]??'';}); return o;}); sheet.diagnostic.recognized=sheet.headers.filter(h=>recognizeHeader(h)); sheet.diagnostic.aliases=sheet.headers.map(h=>({header:h,alias:recognizeHeader(h)})).filter(x=>x.header); sheet.diagnostic.unknown=sheet.headers.filter(h=>h&&!recognizeHeader(h)); sheet.diagnostic.formulas=sheet.rows.reduce((n,r)=>n+r.cells.filter(c=>c.type==='formula').length,0);}
  async function parseWorkbook(file){const zip=await unzipEntries(file); const shared=[]; if(zip.file('xl/sharedStrings.xml')){const doc=xml(await zip.file('xl/sharedStrings.xml').async('text')); doc.querySelectorAll('si').forEach(si=>shared.push([...si.querySelectorAll('t')].map(t=>t.textContent).join('')));} const wb=xml(await zip.file('xl/workbook.xml').async('text')); const relDoc=xml(await zip.file('xl/_rels/workbook.xml.rels').async('text')); const rels={}; relDoc.querySelectorAll('Relationship').forEach(r=>rels[r.getAttribute('Id')]=r.getAttribute('Target')); const sheets=[]; for(const sh of wb.querySelectorAll('sheet')){const name=sh.getAttribute('name'); const rid=sh.getAttribute('r:id')||sh.getAttribute('id'); const path='xl/'+rels[rid].replace(/^\//,''); const doc=xml(await zip.file(path).async('text')); const merges=[...doc.querySelectorAll('mergeCell')].map(m=>m.getAttribute('ref')); const rows=[]; doc.querySelectorAll('sheetData row').forEach(row=>{const values=[], cells=[]; row.querySelectorAll('c').forEach(c=>{const idx=colIndex(colName(c.getAttribute('r'))); const cell=Object.assign({ref:c.getAttribute('r'),index:idx+1},readCell(c,shared)); values[idx]=cell.value; cells.push(cell);}); if(values.some(v=>v!==''&&v!=null)||cells.length)rows.push({number:Number(row.getAttribute('r')),values:values.map(x=>x??''),cells});}); const sheet={name,order:sheets.length+1,dimension:doc.querySelector('dimension')?.getAttribute('ref')||'',merges,rows,headerRow:1,headers:[],objects:[],diagnostic:{recognized:[],unknown:[],aliases:[],mergedCells:merges,formulas:0,validations:doc.querySelectorAll('dataValidation').length}}; buildObjects(sheet); sheets.push(sheet);} const workbook={name:file.name,sheets,originalFileName:file.name,parsedAt:new Date().toISOString()}; workbook.detectedType=classifyWorkbook(workbook,file.name); return workbook;}
  function isInventorySheet(sheet){return hasAliases(sheet,['nodeId','urlDrupal','titleDrupal']);}
  function isRequestSheet(sheet){return hasAliases(sheet,['intentionId','requestTitle','objective','content']);}
  function isSofiaSheet(sheet){return hasAliases(sheet,['sofiaDispositif','sofiaModule','sofiaGroup','session','start','end','modality','uai','location']);}
  function parseXlsxDiagnostic(workbook){const rows=workbook.sheets.flatMap(s=>s.objects.map(o=>Object.assign({sheetName:s.name,rowNumber:o._row},o))); return {workbook,rows,pages:[],diagnostics:workbook.sheets.map(s=>({sheetName:s.name,order:s.order,dimension:s.dimension,headerRow:s.headerRow,columns:s.headers,aliases:s.diagnostic.aliases,mergedCells:s.merges,unknownColumns:s.diagnostic.unknown,formulas:s.diagnostic.formulas,validations:s.diagnostic.validations,isInventory:isInventorySheet(s),isRequest:isRequestSheet(s),isSofia:isSofiaSheet(s)})),warnings:rows.length?[]:['Aucune ligne exploitable détectée dans le classeur.'],errors:[]};}
  async function exportVersionedCopy(workbook, updates=[]){const content=JSON.stringify({type:'excel_inventory_update_plan',version:'2.0',source:workbook?.originalFileName||'',generatedAt:new Date().toISOString(),updates,historyAppendOnly:true,preserveGaiaColumns:true},null,2); return new Blob([content],{type:'application/json'});}
  EAFC.excel={parseWorkbook,parseXlsxDiagnostic,classifyWorkbook,isInventorySheet,isRequestSheet,isSofiaSheet,exportVersionedCopy,recognizeHeader,ALIASES};
})(window.EAFC=window.EAFC||{});
