(function(EAFC){
  EAFC.sessionFiles=EAFC.sessionFiles||new Map();
  async function fingerprint(file){const buf=await file.arrayBuffer(); const hash=await crypto.subtle.digest('SHA-256',buf); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  async function readText(file){return await file.text();}
  function parseJsonText(text){const cleaned=String(text).replace(/^```(?:json)?\s*/,'').replace(/```\s*$/,'').trim(); return JSON.parse(cleaned);}
  function detectJson(obj){if(obj?.plan&&Array.isArray(obj.plan.courses))return 'json_ovp'; if(obj.type==='studio_workspace_v2')return 'studio_workspace'; if(obj.schemaVersion==='2.0'&&obj.jobId)return 'eafc_drupal_job_v2'; if(obj.type==='create_pages'||obj.create_pages||obj.pages)return 'legacy_create_payload'; if(obj.type==='update_drupal_pages'&&obj.version==='3.0')return 'legacy_update_payload'; if(obj.type==='bulk_drupal_theme_public_update')return 'legacy_taxonomy_payload'; if(obj.type==='drupal_update_report'||obj.schemaVersion==='2.0'&&obj.items)return 'drupal_report'; if(obj.items&&obj.version==='1.0')return 'legacy_drupal_sofia_mapping'; return 'json_unknown';}
  function detectByName(name){const n=name.toLowerCase(); if(/\.xlsx?$/.test(n))return 'excel'; if(/\.csv$/.test(n))return n.includes('rana')?'bi_rana':'csv_table'; if(/\.html?$/.test(n))return 'html_table'; if(/\.json$/.test(n))return 'json'; return 'unknown';}
  async function detectFile(file,forcedType=''){const sessionId=EAFC.model.uid('file'); EAFC.sessionFiles.set(sessionId,file); const base={sessionId,name:file.name,size:file.size,date:file.lastModified?new Date(file.lastModified).toISOString():'',fingerprint:'',type:'unknown',rows:0,sheets:0,status:'à analyser',warnings:[],diagnostics:[]}; try{base.fingerprint=await fingerprint(file); const by=detectByName(file.name); base.type=forcedType||by; if(by==='json'||forcedType.startsWith('json')||forcedType.startsWith('legacy')||forcedType==='studio_workspace'||forcedType==='drupal_report'){const obj=parseJsonText(await readText(file)); base.type=forcedType||detectJson(obj); base.rows=Array.isArray(obj.items)?obj.items.length:Array.isArray(obj.plan?.courses)?obj.plan.courses.length:0;} else if(by==='excel'||['recensement_excel','demande_modification_excel','plan_sessions_sofia','excel_unknown'].includes(forcedType)){const wb=await EAFC.excel.parseWorkbook(file); const diag=EAFC.excel.parseXlsxDiagnostic(wb); base.type=forcedType||wb.detectedType; base.sheets=wb.sheets.length; base.rows=diag.rows.length; base.workbook=wb; base.diagnostics=diag.diagnostics; base.warnings.push(...diag.warnings); if(!diag.rows.length)base.warnings.push('Classeur lisible mais aucune ligne exploitable; vérifier les en-têtes.');} base.status='prêt'; }catch(e){base.status='erreur'; base.warnings.push(e.message);} return base;}
  function asArrayOrCount(v){if(Array.isArray(v))return v; if(typeof v==='number')return Array.from({length:v},(_,i)=>i+1); if(EAFC.normalize.isEmpty(v))return []; return [v];}
  function ovpToCanonical(obj, sourceId='ovp'){const courses=obj.plan?.courses||[]; return courses.map((c,i)=>{const meta=c.meta||{}; const m=EAFC.model.createCanonical({intentionId:String(c.id||c.intentionId||c.code||i+1),exportId:String(c.exportId||c.id||''),sourceOvp:obj.plan?.title||sourceId,titleSource:c.title||c.titre||c.name||'',titleDrupal:c.title||c.titre||'',objective:meta.objectif||c.objective||c.objectif||'',content:meta.contenu||c.content||c.contenu||c.description||'',accessibility:meta.accessibilite||c.accessibility||'',prerequisites:meta.prerequis||'',editorialPublic:meta.publicConcerne||'',contact:meta.contact||'',dates:{datesLieux:meta.datesLieux||'',sessionsPresentiel:asArrayOrCount(c.sessionsPresentiel),sessionsDistanciel:asArrayOrCount(c.sessionsDistanciel)},capacity:EAFC.normalize.parseNumber(c.effectif||c.capacity),durationTotal:EAFC.normalize.parseNumber(c.dureeTotale||c.duration||c.duree),durationPresentiel:EAFC.normalize.parseNumber(c.presentiel),durationDistanciel:EAFC.normalize.parseNumber(c.distanciel),departments:EAFC.normalize.departmentsFromText(`${c.title||''} ${c.niveauDeploiement||''}`),status:'imported',typeCandidature:c.typeCandidature||'',niveauDeploiement:c.niveauDeploiement||''}); EAFC.model.addHistory(m,'import_ovp',{sourceId,index:i}); return m;});}
  function getByAlias(row,sheet,alias){const header=sheet.diagnostic.aliases.find(a=>a.alias===alias)?.header; return header?row[header]:'';}
  function splitCodes(v){return [...new Set(String(v||'').split(/[;,|\n\r]+/).map(x=>x.trim()).filter(Boolean))];}
  function inventoryRowsToCanonical(workbook, sourceId='inventory'){const pages=[]; workbook.sheets.forEach(sheet=>{if(!EAFC.excel.isInventorySheet(sheet))return; sheet.objects.forEach(row=>{const get=a=>getByAlias(row,sheet,a); const title=get('titleDrupal'); const moduleCodes=splitCodes(get('moduleGaia')); const dispositifCode=String(get('dispositifGaia')||'').trim(); const m=EAFC.model.createCanonical({nodeId:String(get('nodeId')||''),urlDrupal:get('urlDrupal'),titleDrupal:title,titleSource:title,thematics:EAFC.normalize.splitList(get('thematics')),publics:EAFC.normalize.splitList(get('publics')),departments:splitCodes(get('departments')).length?splitCodes(get('departments')):EAFC.normalize.departmentsFromText(title),trainingCodes:{dispositifCode,moduleCodes},dispositifCode,moduleCodes,objective:get('objective'),content:get('content'),excelOrigin:{sheetName:sheet.name,rowNumber:row._row,sheet:sheet.name,row:row._row},status:get('status')||'inventory'}); EAFC.model.addHistory(m,'import_inventory',{sourceId,sheetName:sheet.name,rowNumber:row._row}); pages.push(m);});}); return pages;}
  function sofiaRows(workbook){const rows=[]; workbook.sheets.forEach(sheet=>{if(!EAFC.excel.isSofiaSheet(sheet))return; sheet.objects.forEach(row=>{const get=a=>getByAlias(row,sheet,a); const dispositifCode=String(get('sofiaDispositif')||'').trim(), moduleCode=String(get('sofiaModule')||'').trim(), groupId=String(get('sofiaGroup')||'').trim(); if(!moduleCode&&!dispositifCode)return; const registered=EAFC.normalize.parseNumber(get('registered')), capacity=EAFC.normalize.parseNumber(get('capacity')); rows.push({dispositifCode,moduleCode,groupId,session:String(get('session')||''),start:get('start'),end:get('end'),modality:get('modality'),uai:String(get('uai')||''),rne:String(get('rne')||''),territory:String(get('territory')||''),location:String(get('location')||''),preRegistrationLink:get('preRegistrationLink'),capacity,registered,remainingSeats:Number.isFinite(capacity)&&Number.isFinite(registered)?capacity-registered:null,excelOrigin:{sheetName:sheet.name,rowNumber:row._row}});});}); return rows;}
  function groupSofiaRows(rows){const map=new Map(); rows.forEach(r=>{const k=[r.dispositifCode,r.moduleCode,r.groupId].join('|'); const g=map.get(k)||Object.assign({},r,{sessions:[],locations:[],uais:[],rnes:[]}); g.sessions.push({session:r.session,start:r.start,end:r.end,modality:r.modality,location:r.location,uai:r.uai,rne:r.rne}); ['locations','uais','rnes'].forEach((field,idx)=>{const val=[r.location,r.uai,r.rne][idx]; if(val&&!g[field].includes(val))g[field].push(val);}); if(!g.preRegistrationLink&&r.preRegistrationLink)g.preRegistrationLink=r.preRegistrationLink; if(g.capacity==null&&r.capacity!=null)g.capacity=r.capacity; if(g.registered==null&&r.registered!=null)g.registered=r.registered; if(g.remainingSeats==null&&r.remainingSeats!=null)g.remainingSeats=r.remainingSeats; map.set(k,g);}); return [...map.values()];}
  async function importDetected(d){if(d.type==='json_ovp') return {models:ovpToCanonical(parseJsonText(await d.file.text()),d.name)}; if(d.type==='recensement_excel') return {models:inventoryRowsToCanonical(d.workbook,d.name), workbook:d.workbook}; if(d.type==='plan_sessions_sofia'){const rows=sofiaRows(d.workbook); return {models:[], workbook:d.workbook, sofiaRows:rows, sofiaGroups:groupSofiaRows(rows)};} return {models:[], workbook:d.workbook||null};}
  async function reparseSourceType(source,newType){const file=EAFC.sessionFiles.get(source.sessionId); if(!file)throw new Error('Fichier original indisponible en mémoire; réimportez le fichier.'); const detected=await detectFile(file,newType); detected.file=file; return detected;}
  EAFC.importers={detectFile,reparseSourceType,detectJson,parseJsonText,ovpToCanonical,inventoryRowsToCanonical,sofiaRows,groupSofiaRows,splitCodes,importDetected};
})(window.EAFC=window.EAFC||{});
