(function(EAFC){
  async function fingerprint(file){const buf=await file.arrayBuffer(); const hash=await crypto.subtle.digest('SHA-256',buf); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  async function readText(file){return await file.text();}
  function parseJsonText(text){const cleaned=String(text).replace(/^```(?:json)?\s*/,'').replace(/```\s*$/,'').trim(); return JSON.parse(cleaned);}
  function detectJson(obj){if(obj.type==='studio_workspace_v2')return 'studio_workspace'; if(obj.schemaVersion==='2.0'&&obj.jobId)return 'eafc_drupal_job_v2'; if(obj.type==='create_pages'||obj.create_pages||obj.pages)return 'legacy_create_payload'; if(obj.type==='update_drupal_pages'&&obj.version==='3.0')return 'legacy_update_payload'; if(obj.type==='bulk_drupal_theme_public_update')return 'legacy_taxonomy_payload'; if(obj.type==='drupal_update_report'||obj.schemaVersion==='2.0'&&obj.items)return 'drupal_report'; if(obj.items&&obj.version==='1.0')return 'legacy_drupal_sofia_mapping'; if(obj.plan&&Array.isArray(obj.plan.courses))return 'json_ovp'; return 'json_unknown';}
  function detectByName(name){const n=name.toLowerCase(); if(/\.xlsx?$/.test(n)){if(n.includes('suivi')||n.includes('recensement'))return 'excel_inventory'; if(n.includes('sofia')||n.includes('plan'))return 'excel_sofia_plan'; return 'excel_request';} if(/\.csv$/.test(n)){if(n.includes('rana'))return 'bi_rana'; return 'csv_table';} if(/\.html?$/.test(n))return 'html_table'; if(/\.json$/.test(n))return 'json'; return 'unknown';}
  async function detectFile(file){const base={name:file.name,size:file.size,date:file.lastModified?new Date(file.lastModified).toISOString():'',fingerprint:'',type:'unknown',rows:0,sheets:0,status:'à analyser',warnings:[]}; try{base.fingerprint=await fingerprint(file); const by=detectByName(file.name); base.type=by; if(by==='json'){const obj=parseJsonText(await readText(file)); base.type=detectJson(obj); base.rows=Array.isArray(obj.items)?obj.items.length:Array.isArray(obj.plan?.courses)?obj.plan.courses.length:0;} else if(by.startsWith('excel')){const wb=await EAFC.excel.parseWorkbook(file); base.sheets=wb.sheets.length; base.rows=wb.sheets.reduce((n,s)=>n+s.rows.length,0); base.workbook=wb; if(wb.sheets.some(s=>EAFC.excel.isInventorySheet(s))) base.type='excel_inventory';} base.status='prêt'; }catch(e){base.status='erreur'; base.warnings.push(e.message);} return base;}
  function ovpToCanonical(obj, sourceId='ovp'){const courses=obj.plan?.courses||[]; return courses.map((c,i)=>{const m=EAFC.model.createCanonical({intentionId:String(c.id||c.intentionId||c.code||i+1),exportId:String(c.exportId||c.id||''),sourceOvp:obj.plan?.title||sourceId,titleSource:c.title||c.titre||c.name||'',titleDrupal:c.title||c.titre||'',objective:c.objective||c.objectif||'',content:c.content||c.contenu||c.description||'',accessibility:c.accessibility||'',capacity:EAFC.normalize.parseNumber(c.capacity||c.effectif),durationTotal:EAFC.normalize.parseNumber(c.duration||c.duree),departments:EAFC.normalize.departmentsFromText(`${c.title||''} ${c.department||''}`),status:'imported'}); EAFC.model.addHistory(m,'import_ovp',{sourceId,index:i}); return m;});}
  function inventoryRowsToCanonical(workbook, sourceId='inventory'){const pages=[]; workbook.sheets.forEach(sheet=>{if(!EAFC.excel.isInventorySheet(sheet))return; sheet.objects.forEach((row,idx)=>{const get=(...aliases)=>aliases.map(a=>row[a]).find(v=>!EAFC.normalize.isEmpty(v))||''; const m=EAFC.model.createCanonical({nodeId:String(get('Node ID Drupal','node id drupal','Node ID')||''),urlDrupal:get('Lien de la page','URL','pageUrl'),titleDrupal:get('Titre','title'),titleSource:get('Titre','title'),thematics:EAFC.normalize.splitList(get('Thématiques saisies')),publics:EAFC.normalize.splitList(get('Métiers')),departments:EAFC.normalize.departmentsFromText(get('Titre')),objective:get('Objectif général du parcours'),content:get('Contenu de la formation'),accessibility:get('Accessibilité de la formation'),implementation:get('Mise en place de la formation'),capacity:EAFC.normalize.parseNumber(get('Effectif :','Effectif')),durationTotal:EAFC.normalize.parseNumber(get('Durée totale du parcours :')),durationPresentiel:EAFC.normalize.parseNumber(get('Durée du présentiel')),durationDistanciel:EAFC.normalize.parseNumber(get('Durée du distanciel :')),editorialPublic:get('Public concerné :'),prerequisites:get('Prérequis du parcours :'),contact:get('Contact de la formation'),excelOrigin:{sheet:sheet.name,row:idx+sheet.headerRow+1},status:get('Statut')||'inventory'}); EAFC.model.addHistory(m,'import_inventory',{sourceId,sheet:sheet.name,row:idx+sheet.headerRow+1}); pages.push(m);});}); return pages;}
  async function importDetected(d){if(d.type==='json_ovp') return {models:ovpToCanonical(parseJsonText(await d.file.text()),d.name)}; if(d.type==='excel_inventory') return {models:inventoryRowsToCanonical(d.workbook,d.name), workbook:d.workbook}; return {models:[], workbook:d.workbook||null};}
  EAFC.importers={detectFile,detectJson,parseJsonText,ovpToCanonical,inventoryRowsToCanonical,importDetected};
})(window.EAFC=window.EAFC||{});
