(function(EAFC){
  const DEPT_FROM_UAI=/^0?(16|17|79|86)/;
  function levenshtein(a,b){a=EAFC.normalize.normalizeTitle(a);b=EAFC.normalize.normalizeTitle(b);const dp=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return dp[a.length][b.length];}
  function titleScore(a,b){const na=EAFC.normalize.normalizeTitle(a), nb=EAFC.normalize.normalizeTitle(b); if(!na||!nb)return 0; if(na===nb)return 1; return Math.max(0,1-levenshtein(na,nb)/Math.max(na.length,nb.length));}
  function getDrupalTitleDepartments(title){const t=String(title||'').trim(); const m=t.match(/^\s*(16|17|79|86|16\s*[\/\\-]\s*17|79\s*[\/\\-]\s*86)\s*[-–—:._ ]+/); if(!m)return []; return [...new Set(m[1].split(/[\/\\-]/).map(x=>x.trim().padStart(2,'0')).map(x=>x.slice(-2)))];}
  function getPlanSessionDepartment(row){const all=[row.uai,row.rne,row.territory,row.location,row.groupId,row.session].join(' '); const u=String(row.uai||row.rne||'').match(DEPT_FROM_UAI); if(u)return u[1]; const m=all.match(/(^|\D)(16|17|79|86)(\D|$)/); return m?m[2]:'';}
  function compatibleDepartment(page,row){const p=(page.departments?.length?page.departments:getDrupalTitleDepartments(page.titleDrupal||page.titleSource)); if(!p.length)return {ok:true,reason:'page académique ou département inconnu'}; const d=getPlanSessionDepartment(row); if(!d)return {ok:false,reason:'département Sofia non résolu'}; return {ok:p.includes(d),reason:p.includes(d)?`département ${d} compatible`:`département ${d} incompatible avec ${p.join('/')}`};}
  function exactModuleMatch(row,page){const code=String(row.moduleCode||row.moduleCodes?.[0]||'').trim(); const mods=page.trainingCodes?.moduleCodes||page.moduleCodes||[]; return code && mods.includes(code);}
  function dispositifControl(row,page){const expected=String(row.dispositifCode||'').trim(); const actual=String(page.trainingCodes?.dispositifCode||page.dispositifCode||'').trim(); return !expected||!actual ? {ok:true,missing:true} : {ok:expected===actual,missing:false};}
  function resolveGaiaToDrupal(sofiaRows,pages){return sofiaRows.map(row=>{const exact=pages.filter(p=>exactModuleMatch(row,p)); const candidates=exact.map(p=>{const dept=compatibleDepartment(p,row), disp=dispositifControl(row,p); const score=(dept.ok?0.95:0.7)+(disp.ok&&!disp.missing?0.04:0); return {nodeId:p.nodeId,pageId:p.canonicalId,title:p.titleDrupal,score:Number(score.toFixed(3)),method:'module_gaia_exact',department:dept,dispositif:disp,blocking:!p.nodeId||!dept.ok||disp.ok===false};}).sort((a,b)=>b.score-a.score); const valid=candidates.filter(c=>!c.blocking); return {row,candidates,best:valid.length===1?valid[0]:null,ambiguous:valid.length>1,blockers:candidates.filter(c=>c.blocking).map(c=>({nodeId:c.nodeId,reason:!c.nodeId?'node_id_missing':(!c.department.ok?'department_mismatch':'dispositif_mismatch')}))};});}
  function fallbackSofiaMatches(page,sofiaRows,manualValidated={}){return sofiaRows.map(row=>{const title=[row.dispositifTitle,row.moduleTitle,row.moduleCode,row.dispositifCode].join(' '); const ts=titleScore(page.titleDrupal||page.titleSource,title); const dept=compatibleDepartment(page,row); const score=Number(((ts*.8)+(dept.ok?.15:0)+((row.uai||row.rne)?0.05:0)).toFixed(3)); const status=score>=.9?'fiable':score>=.75?'probable':score>=.55?'a_verifier':'non_trouve'; return {dispositif:row.dispositifCode,module:row.moduleCode,score,status,groups:[row.groupId].filter(Boolean),sessions:[row.session].filter(Boolean),uai:row.uai,rne:row.rne,lieux:[row.location].filter(Boolean),departments:[getPlanSessionDepartment(row)].filter(Boolean),validated:!!manualValidated[`${page.canonicalId}|${row.moduleCode}|${row.groupId}`],nodeId:page.nodeId};}).sort((a,b)=>b.score-a.score);}
  function getMappingExportBlockers(mapping){const blockers=[]; mapping.forEach(m=>{if(!m.best?.nodeId)blockers.push({type:'node_id_missing',row:m.row}); if(m.ambiguous)blockers.push({type:'ambiguous_node',row:m.row}); (m.blockers||[]).forEach(b=>blockers.push(b));}); return blockers;}
  function scoreCandidate(source,target,rejections={}){const key=`${source.canonicalId}|${target.canonicalId||target.nodeId}`; if(rejections[key]) return null; const reasons=[]; let score=0, method='none'; if(source.nodeId&&target.nodeId&&String(source.nodeId)===String(target.nodeId)){score=1;method='Node ID';reasons.push('Node ID identique');} else if(source.moduleCodes?.length&&target.moduleCodes?.length&&source.moduleCodes.some(x=>target.moduleCodes.includes(x))){score=.9;method='module GAIA exact';reasons.push('module GAIA exact');} else {const checks=[['intentionId',.96,'intention'],['sourceOvp',.93,'source OVP'],['exportId',.9,'export'],['dispositifCode',.84,'dispositif']]; for(const [field,points,label] of checks){if(source[field]&&target[field]&&String(source[field])===String(target[field])){score=points;method=label;reasons.push(`${label} identique`);break;}}}
    if(!score && source.groups?.length && target.groups?.length && source.groups.some(x=>target.groups.includes(x))){score=.76;method='groupe';reasons.push('groupe commun');}
    if(!score && source.rne?.length && target.rne?.length && source.rne.some(x=>target.rne.includes(x))){score=.72;method='RNE';reasons.push('RNE commun');}
    const deptHit=(source.departments||[]).some(d=>(target.departments||[]).includes(d)); if(!score && deptHit){score=.6;method='département';reasons.push('département commun');}
    const ts=titleScore(source.titleSource||source.titleDrupal, target.titleDrupal||target.titleSource); if(ts>.55 && ts>score){score=ts*.55;method='titre normalisé';reasons.push('titre similaire après retrait préfixe départemental');}
    const conflicts=[]; if(deptHit===false && source.departments?.length && target.departments?.length) conflicts.push('départements divergents');
    return {targetId:target.canonicalId, nodeId:target.nodeId, score:Number(score.toFixed(3)), method, reasons, conflicts, dataUsed:{sourceTitle:source.titleSource||source.titleDrupal,targetTitle:target.titleDrupal||target.titleSource, sourceDepartments:source.departments,targetDepartments:target.departments}};}
  function matchAll(sources,targets,rejections={}){return sources.map(s=>{const alternatives=targets.map(t=>scoreCandidate(s,t,rejections)).filter(Boolean).sort((a,b)=>b.score-a.score);const best=alternatives[0]||null;return {sourceId:s.canonicalId,best,alternatives,ambiguous:alternatives[1]&&best&&best.score-alternatives[1].score<.08};});}
  EAFC.matching={titleScore,scoreCandidate,matchAll,getDrupalTitleDepartments,getPlanSessionDepartment,compatibleDepartment,resolveGaiaToDrupal,fallbackSofiaMatches,getMappingExportBlockers};
})(window.EAFC=window.EAFC||{});
