import { nowIso, uid, unique } from './utils.js';
export function createWorkspace() {
  return { schemaVersion: '2.0.0', workspaceId: uid('workspace'), name: 'Espace EAFC', createdAt: nowIso(), updatedAt: nowIso(), currentWorkflow: 'create', stepIndex: 0, sources: [], pages: [], matches: [], diffs: [], reports: [], rejectedMatches: [], selections: {}, removedTargets: {}, controls: [], history: [], undo: [], redo: [], advanced: false };
}
export function makePage(seed = {}) {
  return { canonicalId: seed.canonicalId || uid('page'), intentionOvpId: seed.intentionOvpId || '', exportId: seed.exportId || '', sourceOvp: seed.sourceOvp || '', sourceTitle: seed.sourceTitle || seed.title || '', drupalTitle: seed.drupalTitle || seed.title || '', nodeId: seed.nodeId || '', drupalUrl: seed.drupalUrl || '', pageScope: seed.pageScope || 'academic', excelOrigin: seed.excelOrigin || null, taxonomies: { themes: unique(seed.themes || []), audiences: unique(seed.audiences || []), fancytreePaths: unique(seed.fancytreePaths || []), departments: unique(seed.departments || []), geography: unique(seed.geography || []) }, trainingCodes: { dispositifCode: seed.dispositifCode || '', moduleCodes: unique(seed.moduleCodes || (seed.moduleCode ? [seed.moduleCode] : [])), groups: unique(seed.groups || (seed.groupCode ? [seed.groupCode] : [])), uai: unique(seed.uai || []), rne: unique(seed.rne || (seed.rne ? [seed.rne] : [])) }, sessions: seed.sessions || [], content: { objective: seed.objective || '', body: seed.body || '', accessibility: seed.accessibility || '', setup: seed.setup || '', headcount: seed.headcount || '', totalDuration: seed.totalDuration || '', inPersonDuration: seed.inPersonDuration || '', remoteDuration: seed.remoteDuration || '', editorialPublic: seed.editorialPublic || '', prerequisites: seed.prerequisites || '', contact: seed.contact || '' }, links: seed.links || [], status: seed.status || 'imported', provenance: seed.provenance || {}, confidence: seed.confidence ?? 1, manualValidation: Boolean(seed.manualValidation), errors: seed.errors || [], warnings: seed.warnings || [], history: seed.history || [] };
}
export function addHistory(ws, event, details = {}) { ws.history.push({ eventId: uid('event'), at: nowIso(), event, details }); ws.updatedAt = nowIso(); return ws; }
export function snapshot(ws) { return JSON.stringify({ pages: ws.pages, matches: ws.matches, diffs: ws.diffs, selections: ws.selections, removedTargets: ws.removedTargets, currentWorkflow: ws.currentWorkflow, stepIndex: ws.stepIndex }); }
export function restoreSnapshot(ws, raw) { const data = JSON.parse(raw); Object.assign(ws, data, { updatedAt: nowIso() }); }
export function withUndo(ws, label, mutator) { ws.undo.push({ label, at: nowIso(), snapshot: snapshot(ws) }); ws.redo = []; mutator(ws); addHistory(ws, label); }
export function undo(ws) { const item = ws.undo.pop(); if (!item) return false; ws.redo.push({ label: `redo:${item.label}`, at: nowIso(), snapshot: snapshot(ws) }); restoreSnapshot(ws, item.snapshot); addHistory(ws, 'undo', { label: item.label }); return true; }
export function redo(ws) { const item = ws.redo.pop(); if (!item) return false; ws.undo.push({ label: `undo:${item.label}`, at: nowIso(), snapshot: snapshot(ws) }); restoreSnapshot(ws, item.snapshot); addHistory(ws, 'redo', { label: item.label }); return true; }
