(function(A){
  function workflowOf(target,job){const fields=(target.operations||[]).map(o=>o.field).join(' '); if(job.workflow&&job.workflow!=='mixed')return job.workflow; if(/theme|thematic|public|metiers|taxonomy/.test(fields))return 'update_taxonomy'; if(/session|preinscription|remaining|places|dates|locations/.test(fields))return 'update_sofia'; return target.nodeId?'update_content':'create';}
  async function run(){const st=A.state.get(); if(!st.job)return; st.running=true; st.paused=false; st.stopped=false; if(!st.report)st.report=A.report.init(st.job); A.state.save(); for(;st.index<st.job.targets.length;){if(st.paused||st.stopped)break; const target=st.job.targets[st.index]; await processTarget(target,st.job,st.report); st.index++; st.phase='nextTarget'; A.state.save(); A.ui&&A.ui.render();} st.running=false; if(st.index>=st.job.targets.length)st.report.status=st.report.items.some(i=>i.status==='error')?'partial':'success'; st.report.finishedAt=A.core.now(); A.state.save(); A.ui&&A.ui.render();}
  async function processTarget(target,job,report){const started=performance.now(); const item=A.report.item(target,job); report.items.push(item); const simulation=!!job.safety.simulation; try{phase('validateTarget'); validateTarget(target,job); const wf=workflowOf(target,job); item.workflow=wf; phase('goToPage'); if(wf==='create')await A.navigation.goToCreate(); else await A.navigation.goToTarget(target); phase('openEdit'); if(wf!=='create')await A.navigation.openEdit(target); phase('readBefore'); if(wf!=='create')A.dom.assertNode(target); item.before=A.dom.readKnown(); phase('createBackup'); item.backup=A.core.clone(item.before); report.backup.items.push({target:target.canonicalId,before:item.backup,at:A.core.now()}); phase('applyOperations'); await applyOperations(target,job,wf,item,simulation); phase('verifyAfter'); item.after=A.dom.readKnown(); verifyNoUnexpectedChange(item,target); phase('save'); if(simulation){item.status='simulated'; item.saved=false;} else if(job.safety.autoSave){await A.click.robustClick(A.SELECTORS.save,{label:'Enregistrer',confirm:job.safety.confirmClicks,beforeClick:()=>A.state.save(),delay:job.safety.delayMs}); item.saved=true; item.status='updated';} else {item.status='updated'; item.warnings.push({message:'auto-save désactivé: sauvegarde manuelle requise'});} phase('captureResult'); captureResult(item,target,wf); }catch(e){item.status=e.cancelled?'skipped':'error'; item.errors.push({message:e.message,cancelled:!!e.cancelled}); A.state.log('error',e.message,{target:target.canonicalId});} finally{item.durationMs=Math.round(performance.now()-started); item.attempts=(item.attempts||0)+1;}}
  function phase(p){A.state.set({phase:p}); A.state.log('info',`phase ${p}`);}
  function validateTarget(t,job){if(!t.canonicalId)throw new Error('Cible sans identifiant canonique.'); if(job.workflow!=='create'&&!t.nodeId&&!t.url)throw new Error('Mise à jour sans Node ID ni URL.'); if(!(t.operations||[]).length)throw new Error('Cible sans opération.');}
  async function applyOperations(target,job,wf,item,simulation){for(const op of target.operations){if(!op.field||!op.op)throw new Error('Opération ambiguë.'); if(op.expectedBefore!==undefined){const before=item.before[op.field]??item.before.body??''; if(String(before)&&!String(before).includes(String(op.expectedBefore).slice(0,40))) item.warnings.push({field:op.field,message:'expectedBefore différent ou non vérifiable'});} if(wf==='create') await applyCreate(op,item,simulation); else if(['thematics','theme','publics','metiersPublics','taxonomy'].includes(op.field)) await applyTaxonomy(op,wf,item,simulation); else if(wf==='update_sofia'||['sessions','dates','locations','preinscription','remainingPlaces'].includes(op.field)) item.changedFields.push(op.field), item.after[op.field]=await A.sofia.apply(op,simulation); else await applyContent(op,item,simulation);}}
  async function applyCreate(op,item,simulation){if(op.field==='title')A.dom.setValue(A.SELECTORS.title,op.value,{simulation}); else if(['content','chapo','html'].includes(op.field))await A.ckeditor.write('body',op.value||'',{simulation}); else if(op.field==='media') item.after.media=await A.media.selectBanner(op.value||{},simulation); else if(['thematics','theme'].includes(op.field)) item.after[op.field]=await A.taxonomy.applyTheme(op,'create',simulation); else if(['publics','metiersPublics'].includes(op.field)) item.after[op.field]=await A.taxonomy.applyPublics(Object.assign({},op,{op:'add'}),simulation); else item.after[op.field]=op.value; if(op.field==='content'&&String(op.value||'').includes('places')===false)item.warnings.push({field:op.field,message:'unités places/heures non visibles dans HTML'}); item.changedFields.push(op.field);}
  async function applyTaxonomy(op,wf,item,simulation){if(['thematics','theme'].includes(op.field)) item.after[op.field]=await A.taxonomy.applyTheme(op,wf,simulation); else item.after[op.field]=await A.taxonomy.applyPublics(op,simulation); item.changedFields.push(op.field);}
  async function applyContent(op,item,simulation){const map={title:A.SELECTORS.title,objective:A.SELECTORS.bodyEditor,content:A.SELECTORS.bodyEditor,accessibility:A.SELECTORS.bodyEditor,implementation:A.SELECTORS.bodyEditor,capacity:A.SELECTORS.bodyEditor,durationTotal:A.SELECTORS.bodyEditor,durationPresentiel:A.SELECTORS.bodyEditor,durationDistanciel:A.SELECTORS.bodyEditor,editorialPublic:A.SELECTORS.bodyEditor,prerequisites:A.SELECTORS.bodyEditor,contact:A.SELECTORS.bodyEditor}; if(op.op==='delete')op.value=''; if(op.field==='title')A.dom.setValue(map.title,op.value,{simulation}); else await A.ckeditor.write('body',String(op.value??''),{simulation}); item.changedFields.push(op.field);}
  function verifyNoUnexpectedChange(item,target){const allowed=new Set((target.operations||[]).map(o=>o.field)); Object.keys(item.after||{}).forEach(k=>{if(!allowed.has(k)&&!['body','url','nodeId','title'].includes(k))item.warnings.push({field:k,message:'champ relu non demandé, non modifié par l’Agent'});});}
  function captureResult(item,target,wf){if(wf==='create'){item.nodeId=A.dom.nodeIdFromPage()||item.nodeId; item.url=location.href; item.status=item.status==='simulated'?'simulated':'created';} item.context=document.body.innerText.slice(0,500);}
  A.executor={run,processTarget,workflowOf,validateTarget};
})(window.EAFCAgent=window.EAFCAgent||{});
