import { STUDIO_VERSION, STEPS, WORKFLOWS } from '../core/constants.js';
import { createWorkspace, addHistory, withUndo, undo, redo } from '../core/model.js';
import { inspectFile, allowedSourceTypes } from '../adapters/universal.js';
import { buildSofiaWorkflow, buildEditorialWorkflow, buildTaxonomyWorkflow, WORKFLOW_SOURCE_SLOTS, EDITORIAL_FIELDS, SOFIA_FIELDS, TAXONOMY_FIELDS } from '../core/workflows.js';
import { validateWorkspace } from '../core/validation.js';
import { buildJob, jobFilename } from '../core/exportJob.js';
import { downloadText, escapeHtml, splitTags } from '../core/utils.js';
import { loadWorkspace, saveWorkspace, exportWorkspace, importWorkspace } from '../core/workspace.js';
let ws = loadWorkspace(); let pendingSlot = '';
export function mount(root) { root.innerHTML = layout(); bind(root); recompute(); render(); setInterval(() => saveWorkspace(ws), 10000); }
function layout() { return `<header class="hero"><div><h1>Studio Intranet EAFC v2</h1><p>Préparer des Jobs Drupal sans mélange de sources métier ni transmission externe.</p></div><div class="version">${STUDIO_VERSION}<br><button data-action="resume">Reprendre</button> <button data-action="history">Historique</button> <button data-action="advanced">Options avancées</button></div></header><main><section class="cards">${card('create','Créer de nouvelles pages','Sources : JSON OVP + paramètres de création.')}${card('update_sofia','Actualiser Sofia-FMO','Sources : recensement Drupal + export Sofia-FMO plan et sessions.')}${card('update_content','Appliquer des demandes éditoriales','Sources : recensement Drupal + Excel des demandes.')}${card('update_taxonomy','Modifier les thématiques et publics','Sources : recensement Drupal + choix manuels par Node ID.')}</section><section class="toolbar"><button data-action="import-report">Importer un rapport Drupal</button><button data-action="refresh-inventory">Actualiser le recensement</button><button data-action="export-workspace">Exporter workspace</button><label class="button">Importer workspace<input type="file" data-workspace hidden accept=".json,.studio.json"></label><button data-action="undo">Annuler</button><button data-action="redo">Rétablir</button></section><section class="steps" id="steps"></section><section id="workflow"></section><section class="statusbar" id="statusbar"></section><section class="grid"><div class="main-panel"><div id="sources"></div><div id="filters"></div><div id="table"></div><div id="removed"></div></div><aside id="side"></aside></section><section id="export"></section><input type="file" id="files" multiple hidden><section class="drop advanced-only" id="drop"><strong>Import universel avancé</strong><span>Utilisez de préférence les boutons spécialisés du workflow.</span></section></main>`; }
function card(workflow, title, desc) { return `<button class="card" data-workflow="${workflow}"><h2>${title}</h2><p>${desc}</p></button>`; }
function bind(root) { root.querySelectorAll('[data-workflow]').forEach(btn => btn.onclick = () => { ws.currentWorkflow = btn.dataset.workflow; ws.stepIndex = 1; addHistory(ws, 'workflow', { workflow: ws.currentWorkflow }); recompute(); render(); }); root.querySelector('#files').addEventListener('change', e => importFiles([...e.target.files], pendingSlot)); const drop = root.querySelector('#drop'); ['dragenter','dragover'].forEach(ev => drop.addEventListener(ev, e => { e.preventDefault(); drop.classList.add('drag'); })); ['dragleave','drop'].forEach(ev => drop.addEventListener(ev, e => { e.preventDefault(); drop.classList.remove('drag'); })); drop.addEventListener('drop', e => importFiles([...e.dataTransfer.files], 'advanced')); root.addEventListener('click', onClick); root.addEventListener('input', onInput); root.addEventListener('change', onChange); root.querySelector('[data-workspace]').addEventListener('change', async e => { const f = e.target.files[0]; if (!f) return; ws = importWorkspace(await f.text()); addHistory(ws, 'workspace_imported'); recompute(); render(); }); }
async function importFiles(files, slot = '') { for (const file of files) { let source; try { source = await inspectFile(file); } catch (err) { source = { sourceId: `error-${Date.now()}`, type: 'unsupported_binary', role: slot || 'advanced', name: file.name, lastModified: file.lastModified ? new Date(file.lastModified).toISOString() : '', size: file.size, rows: 0, sheets: 0, status: 'skipped', warnings: [`Fichier ignoré sans bloquer l'extraction : ${err.message}`], errors: [], fingerprint: '', parsed: { rows: [], pages: [], skipped: true } }; } source.importedAt = new Date().toISOString(); source.role = slot || source.type; withUndo(ws, `import_${source.role}`, s => { s.sources.push(source); s.pages.push(...(source.parsed.pages || []).map(p => ({ ...p, sourceRole: source.role }))); if (source.type === 'update_report' || source.type === 'creation_report') s.reports.push(source.parsed.raw); }); } pendingSlot = ''; recompute(); render(); }
function sources(slot) { return ws.sources.filter(s => s.role === slot); }
function pages(role) { return ws.pages.filter(p => p.sourceRole === role && !ws.removedTargets[p.canonicalId]); }
function inventory() { return pages('inventory').filter(p => p.nodeId); }
function recompute() { if (!ws.taxonomySelection) ws.taxonomySelection = { nodeIds: [], themeOperation: 'add', audienceOperation: 'add', themes: [], audiences: [], confirmedDestructive: false }; if (ws.currentWorkflow === WORKFLOWS.updateSofia) { const data = buildSofiaWorkflow(inventory(), sources('sofia').flatMap(s => s.parsed.rows || [])); ws.matches = data.matches; ws.diffs = data.diffs.filter(d => !ws.removedTargets[d.targetId]); } else if (ws.currentWorkflow === WORKFLOWS.updateContent) { const data = buildEditorialWorkflow(inventory(), pages('editorial')); ws.matches = data.matches; ws.diffs = data.diffs.filter(d => !ws.removedTargets[d.targetId]); } else if (ws.currentWorkflow === WORKFLOWS.updateTaxonomy) { ws.diffs = buildTaxonomyWorkflow(inventory(), ws.taxonomySelection).filter(d => !ws.removedTargets[d.targetId]); } else { ws.diffs = []; ws.matches = []; } validateWorkspace(ws); saveWorkspace(ws); }
function render() { document.querySelectorAll('[data-workflow]').forEach(b => b.classList.toggle('active', b.dataset.workflow === ws.currentWorkflow)); renderSteps(); renderWorkflow(); renderStatus(); renderSources(); renderFilters(); renderTable(); renderRemoved(); renderSide(firstActivePage()); renderExport(); document.querySelectorAll('.advanced-only').forEach(el => el.style.display = ws.advanced ? '' : 'none'); }
function renderSteps() { document.getElementById('steps').innerHTML = STEPS.map((s, i) => `<button class="step ${i === ws.stepIndex ? 'active' : ''} ${i < ws.stepIndex ? 'done' : ''}" data-step="${i}">${i+1}. ${s}</button>`).join(''); }
function renderWorkflow() { const slots = WORKFLOW_SOURCE_SLOTS[ws.currentWorkflow] || []; const extra = ws.currentWorkflow === WORKFLOWS.updateTaxonomy ? taxonomyControls() : ''; document.getElementById('workflow').innerHTML = `<section class="workflow"><h2>${workflowTitle()}</h2><div class="source-slots">${slots.map(slot => `<button data-import-slot="${slot.slot}">Importer ${slot.label}</button><span>${sources(slot.slot).length} fichier(s)</span>`).join('')}</div>${extra}</section>`; }
function taxonomyControls() { return `<div class="taxonomy-controls"><label>Node IDs sélectionnés <input data-tax="nodeIds" value="${escapeHtml((ws.taxonomySelection.nodeIds||[]).join(', '))}" placeholder="2524, 2525"></label><label>Opération thématiques <select data-tax="themeOperation">${ops(ws.taxonomySelection.themeOperation)}</select></label><label>Thématiques <input data-tax="themes" value="${escapeHtml((ws.taxonomySelection.themes||[]).join('; '))}"></label><label>Opération publics/métiers <select data-tax="audienceOperation">${ops(ws.taxonomySelection.audienceOperation)}</select></label><label>Publics/métiers Fancytree <input data-tax="audiences" value="${escapeHtml((ws.taxonomySelection.audiences||[]).join('; '))}" placeholder="Catégorie > Public"></label><label><input type="checkbox" data-tax="confirmedDestructive" ${ws.taxonomySelection.confirmedDestructive?'checked':''}> confirmer opérations destructives replace/clear</label></div>`; }
function ops(value) { return ['add','remove','replace','clear'].map(v => `<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join(''); }
function workflowTitle() { return { create:'Créer de nouvelles pages', update_sofia:'Actualiser Sofia-FMO', update_content:'Appliquer des demandes éditoriales', update_taxonomy:'Modifier thématiques et publics' }[ws.currentWorkflow] || ws.currentWorkflow; }
function renderStatus() { const activePages = relevantPages().length; const opsCount = ws.diffs.filter(d => d.selected !== false && !ws.removedTargets[d.targetId]).length; const errors = ws.controls.filter(c => c.level === 'error').length; const warnings = ws.controls.filter(c => c.level === 'warning').length; document.getElementById('statusbar').innerHTML = `<strong>Workflow:</strong> ${ws.currentWorkflow} · <strong>Pages:</strong> ${activePages} · <strong>Opérations:</strong> ${opsCount} · <strong>Erreurs:</strong> ${errors} · <strong>Alertes:</strong> ${warnings} · <strong>Mode:</strong> ${ws.advanced ? 'avancé' : 'simple'}`; }
function renderSources() { document.getElementById('sources').innerHTML = `<h2>Sources</h2><table><thead><tr><th>Rôle</th><th>Type détecté</th><th>Nom</th><th>Lignes</th><th>Feuilles</th><th>Statut</th><th>Avertissements/erreurs</th><th>Empreinte</th></tr></thead><tbody>${ws.sources.map((s,i) => `<tr><td>${escapeHtml(s.role||'')}</td><td><select data-source-type="${i}">${allowedSourceTypes().map(t => `<option ${t===s.type?'selected':''}>${t}</option>`).join('')}</select></td><td>${escapeHtml(s.name)}</td><td>${s.rows}</td><td>${s.sheets}</td><td>${s.status}</td><td>${escapeHtml([...(s.warnings||[]),...(s.errors||[])].join('; '))}</td><td><code>${s.fingerprint.slice(0,12)}</code></td></tr>`).join('') || '<tr><td colspan="8">Aucune source importée.</td></tr>'}</tbody></table>`; document.querySelectorAll('[data-source-type]').forEach(sel => sel.onchange = () => { ws.sources[Number(sel.dataset.sourceType)].type = sel.value; addHistory(ws, 'source_type_override', { index: sel.dataset.sourceType, type: sel.value }); saveWorkspace(ws); render(); }); }
function renderFilters() { document.getElementById('filters').innerHTML = `<h2>Recherche et actions massives</h2><input data-filter="q" placeholder="Rechercher Node ID, titre, intention, dispositif, département" value="${escapeHtml(ws.filterQ||'')}"><button data-action="select-all">Tout sélectionner</button><button data-action="deselect-all">Tout désélectionner</button><button data-action="remove-unselected">Retirer non sélectionnés</button>`; }
function relevantPages() { if (ws.currentWorkflow === WORKFLOWS.create) return pages('ovp'); if (ws.currentWorkflow === WORKFLOWS.updateTaxonomy) return inventory().filter(p => (ws.taxonomySelection.nodeIds||[]).includes(String(p.nodeId))); return inventory(); }
function filteredRows() { const q = (ws.filterQ || '').toLowerCase(); return relevantPages().filter(p => !q || [p.nodeId,p.drupalTitle,p.sourceTitle,p.intentionOvpId,p.trainingCodes.dispositifCode,p.taxonomies.departments.join('/')].join(' ').toLowerCase().includes(q)); }
function renderTable() { const rows = filteredRows(); document.getElementById('table').innerHTML = `<h2>Tableau de travail</h2><table><thead><tr><th>Sélection</th><th>Statut</th><th>Confiance</th><th>Intention</th><th>Page Drupal</th><th>Node ID</th><th>Département</th><th>Dispositif</th><th>Module</th><th>Différences</th><th>Erreurs</th><th>Avertissements</th><th>Actions</th></tr></thead><tbody>${rows.map(p => { const diffs=ws.diffs.filter(d=>d.targetId===p.canonicalId && d.selected !== false).length; const match=ws.matches.find(m=>m.target?.canonicalId===p.canonicalId||m.targetId===p.canonicalId)||{}; return `<tr data-row="${p.canonicalId}"><td><input type="checkbox" data-select-row="${p.canonicalId}" ${ws.selections[p.canonicalId]!==false?'checked':''}></td><td>${escapeHtml(p.status)}</td><td>${match.score??p.confidence}</td><td>${escapeHtml(p.intentionOvpId||p.sourceTitle)}</td><td>${escapeHtml(p.drupalTitle||p.sourceTitle)}</td><td>${escapeHtml(p.nodeId||'')}</td><td>${escapeHtml(p.taxonomies.departments.join('/'))}</td><td>${escapeHtml(p.trainingCodes.dispositifCode)}</td><td>${escapeHtml(p.trainingCodes.moduleCodes.join(','))}</td><td>${diffs}</td><td>${p.errors.length}</td><td>${p.warnings.length}</td><td><button data-remove="${p.canonicalId}">Retirer</button></td></tr>`; }).join('') || '<tr><td colspan="13">Importez les sources attendues pour ce workflow.</td></tr>'}</tbody></table>`; }
function renderRemoved() { const removed = Object.keys(ws.removedTargets || {}).filter(id => ws.removedTargets[id]); document.getElementById('removed').innerHTML = removed.length ? `<h2>Lignes retirées</h2>${removed.map(id => `<button data-restore="${id}">Restaurer ${id}</button>`).join('')}` : ''; }
function firstActivePage() { return filteredRows()[0] || relevantPages()[0]; }
function renderSide(p) { const diffs = p ? ws.diffs.filter(d => d.targetId === p.canonicalId) : []; document.getElementById('side').innerHTML = `<h2>Fiche latérale</h2>${p ? `<h3>${escapeHtml(p.drupalTitle||p.sourceTitle)}</h3><p><strong>Node ID:</strong> ${escapeHtml(p.nodeId||'création')}</p><details open><summary>Valeurs actuelles / demandées</summary><pre>${escapeHtml(JSON.stringify({ content:p.content,taxonomies:p.taxonomies,sessions:p.sessions,diffs },null,2))}</pre></details><details open><summary>Prévisualisation</summary><article>${p.content.body||'<em>Aucun HTML principal.</em>'}</article><p>Lien de retour prévu : Retour à la page Ma formation</p></details><details><summary>Correspondances</summary><pre>${escapeHtml(JSON.stringify(ws.matches.filter(m=>m.target?.canonicalId===p.canonicalId||m.targetId===p.canonicalId),null,2))}</pre></details><details><summary>Rapport Agent</summary><pre>${escapeHtml(JSON.stringify(reportFor(p),null,2))}</pre></details>` : '<p>Aucune page sélectionnée.</p>'}`; }
function reportFor(p) { return ws.reports.flatMap(r => r.items || []).find(i => i.canonicalId === p.canonicalId || i.nodeId === p.nodeId) || {}; }
function renderExport() { const validation = validateWorkspace(ws); const job = buildJob(ws); document.getElementById('export').innerHTML = `<h2>Contrôles et export</h2><div>${ws.controls.map(c => `<p class="${c.level}">${c.level === 'error' ? '⛔' : '⚠️'} ${escapeHtml(c.message)}</p>`).join('') || '<p class="ok">Aucun blocage détecté.</p>'}</div><button data-action="run-controls">Relancer contrôles</button><button data-action="download-job" ${validation.blocking?'disabled':''}>Exporter ${jobFilename(job)}</button><button data-action="download-inventory">Exporter copie recensement confirmée</button><pre>${escapeHtml(JSON.stringify(job,null,2))}</pre>`; }
function onInput(e) { if (e.target.dataset.filter === 'q') { ws.filterQ = e.target.value; renderTable(); } if (e.target.dataset.tax) { updateTax(e.target); recompute(); render(); } }
function onChange(e) { if (e.target.dataset.selectRow) { ws.selections[e.target.dataset.selectRow] = e.target.checked; } if (e.target.dataset.tax) { updateTax(e.target); recompute(); render(); } }
function updateTax(el) { const key = el.dataset.tax; if (key === 'nodeIds') ws.taxonomySelection.nodeIds = splitTags(el.value.replace(/,/g,';')).map(String); else if (key === 'themes' || key === 'audiences') ws.taxonomySelection[key] = splitTags(el.value); else if (key === 'confirmedDestructive') ws.taxonomySelection[key] = el.checked; else ws.taxonomySelection[key] = el.value; }
function onClick(e) { const a = e.target.dataset.action; if (e.target.dataset.step) { ws.stepIndex = Number(e.target.dataset.step); render(); } if (e.target.dataset.importSlot) { pendingSlot = e.target.dataset.importSlot; document.getElementById('files').click(); } if (e.target.dataset.remove) { withUndo(ws, 'remove_target', s => { s.removedTargets[e.target.dataset.remove] = true; s.diffs = s.diffs.filter(d => d.targetId !== e.target.dataset.remove); }); recompute(); render(); } if (e.target.dataset.restore) { withUndo(ws, 'restore_target', s => { delete s.removedTargets[e.target.dataset.restore]; }); recompute(); render(); } if (a === 'advanced') { ws.advanced = !ws.advanced; render(); } if (a === 'undo') { undo(ws); recompute(); render(); } if (a === 'redo') { redo(ws); recompute(); render(); } if (a === 'export-workspace') downloadText(`studio-eafc-${ws.workspaceId}.studio.json`, exportWorkspace(ws)); if (a === 'download-job') { const job = buildJob(ws); downloadText(jobFilename(job), JSON.stringify(job,null,2)); } if (a === 'download-inventory') downloadText(`recensement-eafc-v2-${new Date().toISOString().slice(0,10)}.csv`, buildInventoryCsv(), 'text/csv'); if (a === 'resume') { ws = loadWorkspace(); recompute(); render(); } if (a === 'history') alert(ws.history.map(h => `${h.at} ${h.event}`).join('\n') || 'Historique vide'); if (a === 'import-report') { pendingSlot = 'report'; document.getElementById('files').click(); } if (a === 'refresh-inventory') downloadText(`recensement-confirme-${new Date().toISOString().slice(0,10)}.csv`, buildInventoryCsv(), 'text/csv'); if (a === 'run-controls') { validateWorkspace(ws); renderExport(); } if (a === 'select-all') { filteredRows().forEach(p => ws.selections[p.canonicalId] = true); renderTable(); } if (a === 'deselect-all') { filteredRows().forEach(p => ws.selections[p.canonicalId] = false); renderTable(); } if (a === 'remove-unselected') { withUndo(ws, 'remove_unselected', s => filteredRows().filter(p => s.selections[p.canonicalId] === false).forEach(p => { s.removedTargets[p.canonicalId] = true; })); recompute(); render(); } }
function buildInventoryCsv() { const reportItems = ws.reports.flatMap(r => r.items || []).filter(i => ['success','warning'].includes(i.status)); const rows = [['Node ID','URL','Statut','Job ID','Champs modifiés','Ancienne valeur','Nouvelle valeur','Erreurs','Version outil']]; for (const p of inventory()) { const ri = reportItems.find(i => i.nodeId === p.nodeId || i.canonicalId === p.canonicalId); rows.push([p.nodeId,p.drupalUrl,ri?.status||p.status,ws.reports.slice(-1)[0]?.jobId||'',(ri?.operationsApplied||[]).map(o=>o.field).join('|'),JSON.stringify(ri?.before||{}),JSON.stringify(ri?.after||{}),(ri?.errors||[]).map(e=>e.message||e).join('|'),STUDIO_VERSION]); } rows.push(['HISTORIQUE',new Date().toISOString(),'append-only','','','','','','']); return rows.map(r => r.map(v => `"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n'); }
